accounts/urls.py
"""Accounts URL's config"""

from django.urls import path

from rest_framework import routers

from . import views


app_name = 'accounts'

urlpatterns = [
    path('<int:id>/', views.nombre, name='nombre'),
    path('login/', views.signin, name='login'),
    path('login-class/', views.LoginView.as_view(), name='login_class'),
    path('profile/', views.perfil, name='profile'),
    path('logout/', views.signoff, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('signup-class/', views.SignupView.as_view(), name='signup_class'),
]

bedu_django/urls.py
"""Bedu Django URL Configuration"""

from django.contrib import admin
from django.urls import path, include

from rest_framework import routers

from cats import views as cats_views
from accounts import views as accounts_views

router = routers.DefaultRouter()
router.register('cats', cats_views.CatViewSet)
router.register('api/accounts', accounts_views.UserViewset)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + router.urls

cats/urls.py
"""Cats app URLs config"""

from django.urls import path

from rest_framework import routers

from . import views


app_name = 'cats'

urlpatterns = [
    path('hola-mundo/', views.index, name='index'),
] + router.urls

accounts/models.py
from django.db import models

# Create your models here.

cats/models.py
"""Cats app models"""

from django.contrib.auth.models import User
from django.db import models


class Cat(models.Model):
    """Cat model"""
    name = models.CharField(max_length=15)
    breed = models.CharField(max_length=15)
    birthday = models.DateField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name + ' (' + self.breed + ')'

accounts/forms.py
"""Accounts forms"""

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password


class SignupForm(forms.Form):
    """User form"""
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    password_confirmation = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user_exists = User.objects.filter(username=username).exists()

        if user_exists:
            raise forms.ValidationError('El nombre de usuario ya existe.')

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        email_exists = User.objects.filter(email=email).exists()

        if email_exists:
            raise forms.ValidationError('El correo ya existe.')

        return email

    
    def clean(self):
        data = super().clean()
        password = data.get('password')
        password_confirmation = data.get('password_confirmation')

        if not password or password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden')

        validate_password(password)

        return data


    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')
        return User.objects.create_user(**data)

accounts/views.py
"""Accounts views"""

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic import FormView


from rest_framework import viewsets

from .forms import SignupForm
from .serializers import UserSerializer


class LoginView(auth_views.LoginView):
    template_name = 'accounts/login.html'
    redirect_field_name = reverse_lazy('accounts:profile')


class SignupView(FormView):
    form_class = SignupForm
    success_url = reverse_lazy('accounts:profile')
    template_name = 'accounts/signup.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


class UserViewset(viewsets.ModelViewSet):
    """User viewset"""
    queryset = User.objects.all()
    serializer_class = UserSerializer


def signin(request):
    if request.method == 'GET':
        return render(request, 'accounts/login.html')
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect('accounts:profile')
        else:
            return render(request, 'accounts/login.html', {
                'message': 'Tus credenciales no existen'
            })


@login_required
def perfil(request):
    return render(request, 'accounts/perfil.html')


def signoff(request):
    logout(request)
    return redirect('accounts:login')


def signup(request):
    if request.method == 'GET':
        form = SignupForm()

    else:
        form = SignupForm(data=request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:profile')

    return render(request, 'accounts/signup.html', {'form': form})


def nombre(request, id):
    from django.http import HttpResponse
    username = User.objects.get(id=id).username
    return HttpResponse('<h1>Hola, {}</h1>'.format(username))

cats/views.py
"""Cats app views"""

# Nativas

# Django
from django.http import JsonResponse

# Third-party
from rest_framework import viewsets

# Locales
from .models import Cat
from .serializers import CatSerializer


def index(request):
    return JsonResponse({
        'message': 'Hola mundo'
    })



class CatViewSet(viewsets.ModelViewSet):
    queryset = Cat.objects.all()
    serializer_class = CatSerializer

templates/accounts/login.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <style>
      form {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
      }
    </style>
    <title>Bedu Django</title>
  </head>
  <body>
    {% if message %}
    <h1>{{ message }}</h1>
    {% endif %}

    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      <p>
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" />
      </p>
      <p>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" />
      </p>
      <button type="submit">¡Iniciar sesión!</button>
    </form>
  </body>
</html>

templates/accounts/perfil.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <style>
      h1,
      p, a {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
      }
    </style>
    <title>Bedu Django</title>
  </head>
  <body>
    <h1>Perfil</h1>

    {% if request.user.is_authenticated %}
      <p>{{ request.user.username }}</p>
      <p>{{ request.user.email }}</p>
      <a href="{% url 'accounts:logout' %}">
        <button>Cerrar sesión</button>
      </a>
    {% else %}
      <p>Primero inicia sesión</p>
    {% endif %}
  </body>
</html>

templates/accounts/signup.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <style>
      form {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
      }
    </style>
    <title>Bedu Django</title>
  </head>
  <body>
      
    {% for error in form.username.errors %}
      <h3 style="color: red;">{{error}}</h3>
    {% endfor %}

    {% for error in form.email.errors %}
      <h3 style="color: red;">{{error}}</h3>
    {% endfor %}

    {% for error in form.non_field.errors %}
    <h3 style="color: red;">{{error}}</h3>
    {% endfor %}      

    <form action="{% url 'accounts:signup' %}" method="POST">
      <h1>Regístrate</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">¡Crear cuenta!</button>
    </form>
  </body>
</html>